title: Prachi Mulmi
logo: "/images/logo.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Prachi and I graduated from Mount Holyoke College in May 2021 with a B.A. in Computer Science.
  <br><br>
  I am looking for full time opportunities in software development in the U.S.
  <br><br>
  <a href = "https://www.linkedin.com/in/prachi-mulmi/">View My LinkedIn Profile</a> 
  <br><br>
  <a href = "https://www.github.com/prachimulmi">View My Github Profile</a>
  <br><br>   
theme: jekyll-theme-minimal
